package None;

import java.util.List;
import lombok.*;






/**
  A Dataset that was generated by an analysis of some previously generated data. For example, a dataset that contains the data of an assignment of a chemical structure to a sample based on the spectral data obtained from the sample is an AnalyticalDataset.
**/
@Data
@EqualsAndHashCode(callSuper=false)
public class AnalysisDataset extends Dataset {


}