# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2025'
email: philip.stroemert@tib.eu
full_name: Philip Strömert
gh_action_docs_preview: true
gh_action_pypi: true
github_org: nfdi-de
license: MIT
project_description: "This metadata schema is an Extension of the DCAT Application\
    \ Profile for Providing Links to Use-case Specific Context. It allows to provide\
    \ additional metadata regarding: which kind(s) of entity(s) or activity(s)\
    \ were evaluated (the dcat:Dataset is about), which kind of activity generated\
    \ the dcat:Dataset, which kind of instruments were used in the dataset generating\
    \ activity, in which surrounding (e.g. a laboratory) and according to which\
    \ plan the dataset generating activity took place, as well as regarding which\
    \ kind(s) of qualitative and quantitative characteristic were attributed to\
    \ the evaluated entity or evaluated activity and to the used instruments."
project_name: dcat-ap-plus
project_slug: dcat_ap_plus

